### ISSUE TITLE
Dont suggest to override print function - it prevents errors from being printed

### ISSUE THREAD

**Issue by srghma** [bcaudan/jasmine-spec-reporter#375]
Here you suggest override print function

https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples/protractor#remove-protractor-dot-reporter

with `print: function() {}`

```
/app/packages/feature-tests # npm run test

> @myproject/feature-tests@1.0.0 test /app/packages/feature-tests
> protractor ./config.js

[12:08:25] I/launcher - Running 1 instances of WebDriver
[12:08:25] I/hosted - Using the selenium server at http://hub:4444/wd/hub
Jasmine started

  Materials

    Index
      ✗ Should fetch materials of project
        - Failed: project is not defined

**************************************************
*                    Failures                    *
**************************************************

1) Materials Index Should fetch materials of project
  - Failed: project is not defined

Executed 1 of 16 specs (1 FAILED) (15 SKIPPED) in 2 secs.
[12:08:29] I/launcher - 0 instance(s) of WebDriver still running
[12:08:29] I/launcher - chrome #01 failed 1 test(s)
[12:08:29] I/launcher - overall: 1 failed spec(s)
[12:08:29] E/launcher - Process exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @myproject/feature-tests@1.0.0 test: `protractor ./config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @myproject/feature-tests@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-05T12_08_29_745Z-debug.log
```

without `print: function() {}`

```
/app/packages/feature-tests # npm run test

> @myproject/feature-tests@1.0.0 test /app/packages/feature-tests
> protractor ./config.js

[12:08:11] I/launcher - Running 1 instances of WebDriver
[12:08:11] I/hosted - Using the selenium server at http://hub:4444/wd/hub
Started
Jasmine started
F
  Materials

    Index
      ✗ Should fetch materials of project
        - Failed: project is not defined



Failures:
1) Materials Index Should fetch materials of project
  Message:
    Failed: project is not defined
  Stack:
    ReferenceError: project is not defined
        at UserContext.project (/app/packages/feature-tests/src/specs/materials/index/index.js:59:38)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From: Task: Run it("Should fetch materials of project") in control flow
        at UserContext.<anonymous> (/app/packages/feature-tests/node_modules/jasminewd2/index.js:94:19)
        at /app/packages/feature-tests/node_modules/jasminewd2/index.js:64:48
        at ControlFlow.emit (/app/packages/feature-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/events.js:62:21)
        at ControlFlow.shutdown_ (/app/packages/feature-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2674:10)
        at shutdownTask_.MicroTask (/app/packages/feature-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2599:53)
        at MicroTask.asyncRun (/app/packages/feature-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2728:9)
        at /app/packages/feature-tests/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
    From asynchronous test:
    Error
        at Suite.it (/app/packages/feature-tests/src/specs/materials/index/index.js:56:5)
        at Suite.describe (/app/packages/feature-tests/src/specs/materials/index/index.js:23:3)
        at Object.fdescribe (/app/packages/feature-tests/src/specs/materials/index/index.js:22:1)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
        at Module._compile (/app/packages/feature-tests/node_modules/pirates/lib/index.js:83:24)
        at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Object.newLoader [as .js] (/app/packages/feature-tests/node_modules/pirates/lib/index.js:88:7)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

Ran 1 of 16 specs
1 spec, 1 failure
Finished in 2.703 seconds

**************************************************
*                    Failures                    *
**************************************************

1) Materials Index Should fetch materials of project
  - Failed: project is not defined

Executed 1 of 16 specs (1 FAILED) (15 SKIPPED) in 3 secs.
[12:08:15] I/launcher - 0 instance(s) of WebDriver still running
[12:08:15] I/launcher - chrome #01 failed 1 test(s)
[12:08:15] I/launcher - overall: 1 failed spec(s)
[12:08:15] E/launcher - Process exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @myproject/feature-tests@1.0.0 test: `protractor ./config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @myproject/feature-tests@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-05T12_08_15_879Z-debug.log
```

**Comment by bcaudan** [comment]
without `print: function() {}`, you have output from both jasmine-spec-reporter and the default protractor reporter.
You should have an equivalent output with the configuration:
```js
{
  summary: {
    displayStacktrace: true
  }
}
```
You can find available configuration options [here](https://github.com/bcaudan/jasmine-spec-reporter/blob/master/src/configuration.ts).

**Comment by srghma** [comment]
oops, I had it equal to false
