### ISSUE TITLE
Feature: using with jasmine --reporter command line switch

### ISSUE THREAD

**Issue by apla** [bcaudan/jasmine-spec-reporter#392]
- [x] I have this issue with the latest release of [jasmine-spec-reporter](https://github.com/bcaudan/jasmine-spec-reporter/releases) - 4.2.1
- [x] I have this issue with the latest release of [jasmine](https://github.com/jasmine/jasmine/releases) 3.3.1
- [x] I can reproduce this issue with one of the [examples](https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples)

**Current behavior**

`jasmine` allows to use reporter as a command line option, like `jasmine --reporter=jasmine-spec-reporter`, but `jasmine-spec-reporter` itself is not compatible. 

```
failed to register reporter "jasmine-spec-reporter"
Report is not a constructor
TypeError: Report is not a constructor
    at runJasmine (/More/work/rian/mediafacade/node_modules/jasmine/lib/command.js:148:22)
    at Command.run (/More/work/rian/mediafacade/node_modules/jasmine/lib/command.js:56:9)
    at Object.<anonymous> (/More/work/rian/mediafacade/node_modules/jasmine/bin/jasmine.js:11:9)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

Also I tried `jasmine --reporter=jasmine-spec-reporter/built/spec-reporter.js`. In this case, no error reported, but also reporter not works.

**Comment by bcaudan** [comment]
This feature seems handy but it can only be used with the default configuration of `jasmine-spec-reporter`.
This feature expect that the reporter module export a constructor (https://github.com/jasmine/jasmine/issues/1027#issuecomment-360873492) but currently `jasmine-spec-reporter` export:
- `SpecReporter`: the reporter constructor
- `DisplayProcessor`: the class to extend to [customize the reporter output](https://github.com/bcaudan/jasmine-spec-reporter/blob/master/docs/customize-output.md#build-your-display-processor)

A way to do that without breaking the current exports could be to have a dedicated node module with only the constructor exported. IMO, it sounds a bit complicated for the benefit of this feature.

Any thoughts?

**Comment by kuebk** [comment]
Would love to get this working! <3

**Comment by bcaudan** [comment]
I have submitted a PR to jasmine-npm, https://github.com/jasmine/jasmine-npm/pull/159.
