### ISSUE TITLE
TypeError: Cannot read property 'order' of undefined

### ISSUE THREAD

**Issue by innovate-invent** [bcaudan/jasmine-spec-reporter#512]
There is a disagreement between this package and jasmine-json-stream-reporter on the presence of a rundetails argument to jasmineDone().

This causes an exception to be thrown during tests.

https://github.com/bcaudan/jasmine-spec-reporter/blob/01fdfd3a8d90e7f0ce594de962f6cd8197342f48/src/execution-metrics.ts#L36-L37

See https://github.com/rdy/jasmine-json-stream-reporter/issues/9

```
TypeError: Cannot read property 'order' of undefined
    at ExecutionMetrics.stop (/home/nolan/Projects/socprox/node_modules/jasmine-spec-reporter/built/execution-metrics.js:27:34)
    at SpecReporter.jasmineDone (/home/nolan/Projects/socprox/node_modules/jasmine-spec-reporter/built/spec-reporter.js:54:22)
    at /home/nolan/Projects/socprox/node_modules/jasmine-json-stream-reporter/to-reporter.js:68:23
    at Array.forEach (<anonymous>)
    at DestroyableTransform._flush (/home/nolan/Projects/socprox/node_modules/jasmine-json-stream-reporter/to-reporter.js:67:15)
    at DestroyableTransform.prefinish (/home/nolan/Projects/socprox/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:315:20)
    at DestroyableTransform.EventEmitter.emit (domain.js:547:15)
    at prefinish (/home/nolan/Projects/socprox/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/home/nolan/Projects/socprox/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/home/nolan/Projects/socprox/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/home/nolan/Projects/socprox/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at Stream.onend (internal/streams/legacy.js:46:10)
    at Stream.emit (events.js:327:22)
    at Stream.EventEmitter.emit (domain.js:547:15)
    at drain (/home/nolan/Projects/socprox/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/home/nolan/Projects/socprox/node_modules/through/index.js:45:5)
    at /home/nolan/Projects/socprox/node_modules/flat-map/flat-map.js:64:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by bcaudan** [comment]
Hello @innovate-invent,

I had a quick look at jasmine-json-stream-reporter and it is not clear to me how you can use it and how it is related to jasmine-spec-reporter.
Could you provide more info on what you are trying to achieve and how?

**Comment by innovate-invent** [comment]
Here is a copy of my gulp file:

```js
// https://github.com/jasmine/gulp-jasmine-browser#usage-with-webpack
const gulp = require('gulp');
const jasmineBrowser = require('gulp-jasmine-browser');
const webpack = require('webpack-stream');
const JasminePlugin = require('gulp-jasmine-browser/webpack/jasmine-plugin');
const webpack_config = require('./webpack.config');
const JasmineSpecReporter = require('jasmine-spec-reporter');

function jasmine() {
    const plugin = new JasminePlugin();
    return gulp.src(['spec/**/*_spec.ts'])
        .pipe(webpack({watch: false, output: {filename: 'spec.js'}, plugins: [plugin], module: webpack_config.module, resolve: webpack_config.resolve, mode: webpack_config.mode}))
        .pipe(jasmineBrowser.specRunner({console: true}))
        .pipe(jasmineBrowser.headless({driver: 'chrome', catch: true, random: true, sourcemappedStacktrace: true, args:['--ignore-certificate-errors'], ignoreHTTPSErrors:true, reporter: new JasmineSpecReporter.SpecReporter()}));
}

exports.default = jasmine;
```

Running this throws the stack-trace in my initial message.

**Comment by bcaudan** [comment]
FMU, this issue is on jasmine-json-stream-reporter side.
Feel free to reopen otherwise.
